In [59]:
import pandas as pd

In [62]:
!pip install xgboost

In [63]:
import pandas as pd
import xgboost as xgb
import numpy as np
import collections
import witwidget

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.utils import shuffle
from witwidget.notebook.visualization import WitWidget, WitConfigBuilder

In [64]:
# if you get error in xgboost
# run
# conda install -c conda-forge xgboost

In [65]:
import pandas as pd

In [66]:
data = pd.read_csv('diabetes.csv')

In [67]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [68]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
# Split the data into train / test sets
y = data['Outcome']
x = data[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']]
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=1234)

In [71]:
# Train the model, this will take a few minutes to run
bst = xgb.XGBClassifier(
    objective='reg:logistic'
)

bst.fit(x_train, y_train)

The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=4, num_parallel_tree=1,
              objective='reg:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [72]:
# Get predictions on the test set and print the accuracy score
y_pred = bst.predict(x_test)
acc = accuracy_score(np.array(y_test), y_pred)
print(acc, '\n')

0.7291666666666666 



In [73]:
# Print a confusion matrix
print('Confusion matrix:')
cm = confusion_matrix(y_test, y_pred)
print(cm)

Confusion matrix:
[[101  20]
 [ 32  39]]


In [74]:
# Save the model so we can deploy it
bst.save_model('model.bst')

In [75]:
bst

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=4, num_parallel_tree=1,
              objective='reg:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [77]:
x_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
8              2      197             70             45      543  30.5   
719            5       97             76             27        0  35.6   
296            2      146             70             38      360  28.0   
651            1      117             60             23      106  33.8   
93             4      134             72              0        0  23.8   

     DiabetesPedigreeFunction  Age  
8                       0.158   53  
719                     0.378   52  
296                     0.337   29  
651                     0.466   27  
93                      0.277   60

In [78]:
bst.predict(x_train.head())

array([1, 1, 1, 0, 1])

In [79]:
y_train.head()

8      1
719    1
296    1
651    0
93     1
Name: Outcome, dtype: int64

In [80]:
x_train.iloc[3] = x_train.iloc[1]


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [81]:
x_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
8              2      197             70             45      543  30.5   
719            5       97             76             27        0  35.6   
296            2      146             70             38      360  28.0   
651            5       97             76             27        0  35.6   
93             4      134             72              0        0  23.8   

     DiabetesPedigreeFunction  Age  
8                       0.158   53  
719                     0.378   52  
296                     0.337   29  
651                     0.378   52  
93                      0.277   60

In [82]:
bst.predict(x_train.head())

array([1, 1, 1, 1, 1])

In [83]:
x_train.iloc[3] = [1, 117, 60, 23, 106, 33.8, 0.466, 27]


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [84]:
x_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
8              2      197             70             45      543  30.5   
719            5       97             76             27        0  35.6   
296            2      146             70             38      360  28.0   
651            1      117             60             23      106  33.8   
93             4      134             72              0        0  23.8   

     DiabetesPedigreeFunction  Age  
8                       0.158   53  
719                     0.378   52  
296                     0.337   29  
651                     0.466   27  
93                      0.277   60

In [85]:
result = pd.DataFrame()
result['features_importance'] = bst.feature_importances_
result['feature_names'] = x_train.columns
result.sort_values(by=['features_importance'],ascending=False)

features_importance             feature_names
1             0.256590                   Glucose
5             0.150868                       BMI
7             0.122263                       Age
4             0.111036                   Insulin
6             0.096079  DiabetesPedigreeFunction
3             0.093502             SkinThickness
0             0.087773               Pregnancies
2             0.081890             BloodPressure

In [86]:
# we will make small changes to the values
x_train.iloc[2] = [2, 146, 70, 38, 360, 28.0, 0.337, 29]
x_train.iloc[2]
x_train.columns


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [87]:
bst.predict(x_train.head())

array([1, 1, 1, 0, 1])

In [88]:
y_train.head()

8      1
719    1
296    1
651    0
93     1
Name: Outcome, dtype: int64

In [89]:
# if we change the important features such as Glucose and Age

x_train.iloc[2] = [3, 117, 76, 36, 245, 31.6, 0.851, 27]
x_train.iloc[2]
x_train.columns

bst.predict(x_train.head())

y_train.head()

8      1
719    1
296    1
651    0
93     1
Name: Outcome, dtype: int64

In [90]:
# if we change the important features such as Glucose, BMI and Age

x_train.iloc[2] = [3, 117, 76, 36, 245, 30.6, 0.851, 29]
x_train.iloc[2]
x_train.columns

bst.predict(x_train.head())

y_train.head()

8      1
719    1
296    1
651    0
93     1
Name: Outcome, dtype: int64

In [91]:
import tensorflow as tf
tf.get_logger().setLevel(40) # suppress deprecation messages
tf.compat.v1.disable_v2_behavior() # disable TF2 behaviour as alibi code still relies on TF1 constructs
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.utils import to_categorical
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import os
from alibi.explainers import CounterFactualProto

print('TF version: ', tf.__version__)
print('Eager execution enabled: ', tf.executing_eagerly()) # False

TF version:  2.4.1
Eager execution enabled:  False


In [92]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((576, 8), (576,), (192, 8), (192,))

In [93]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [94]:
np.random.seed(42)
tf.random.set_seed(42)

In [95]:
def nn_model():
    x_in = Input(shape=(8,))
    x = Dense(40, activation='relu')(x_in)
    x = Dense(40, activation='relu')(x)
    x_out = Dense(2, activation='softmax')(x)
    nn = Model(inputs=x_in, outputs=x_out)
    nn.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
    return nn

In [96]:
nn = nn_model()
nn.summary()
nn.fit(x_train, y_train, batch_size=64, epochs=500, verbose=0)
nn.save('nn_diabetes.h5', save_format='h5')

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 8)]               0         
_________________________________________________________________
dense_3 (Dense)              (None, 40)                360       
_________________________________________________________________
dense_4 (Dense)              (None, 40)                1640      
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 82        
Total params: 2,082
Trainable params: 2,082
Non-trainable params: 0
_________________________________________________________________


In [97]:
nn = load_model('nn_diabetes.h5')
score = nn.evaluate(x_test, y_test, verbose=0)
print('Test accuracy: ', score[1])

Test accuracy:  0.71875


`Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.


In [98]:
#Generate counterfactual guided by the nearest class prototype

In [99]:
X = np.array(x_test)[1].reshape((1,) + np.array(x_test)[1].shape)
shape = X.shape

In [100]:
shape

(1, 8)

In [101]:
# define model
nn = load_model('nn_diabetes.h5')

predict_fn = lambda x: nn.predict(x)

# initialize explainer, fit and generate counterfactual
cf = CounterFactualProto(predict_fn, shape, use_kdtree=False, theta=10., max_iterations=1000,
                         feature_range=(np.array(x_train).min(axis=0), np.array(x_train).max(axis=0)),
                         c_init=1., c_steps=10)
cf.fit(x_train)

CounterFactualProto(meta={
  'name': 'CounterFactualProto',
  'type': ['blackbox', 'tensorflow', 'keras'],
  'explanations': ['local'],
  'params': {
              'kappa': 0.0,
              'beta': 0.1,
              'feature_range': (array([ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.078, 21.   ]), array([ 15.  , 198.  , 122.  ,  63.  , 846.  ,  67.1 ,   2.42,  81.  ])),
              'gamma': 0.0,
              'theta': 10.0,
              'cat_vars': None,
              'ohe': False,
              'use_kdtree': False,
              'learning_rate_init': 0.01,
              'max_iterations': 1000,
              'c_init': 1.0,
              'c_steps': 10,
              'eps': (0.001, 0.001),
              'clip': (-1000.0, 1000.0),
              'update_num_grad': 1,
              'write_dir': None,
              'shape': (1, 8),
              'is_model': False,
              'is_model_keras': False,
              'is_ae': False,
              'is_ae_keras': False,
          

In [102]:
x_train.min(axis=0)

Pregnancies                  0.000
Glucose                      0.000
BloodPressure                0.000
SkinThickness                0.000
Insulin                      0.000
BMI                          0.000
DiabetesPedigreeFunction     0.078
Age                         21.000
dtype: float64

In [103]:
explanation = cf.explain(X)

In [106]:
print(explanation)

Explanation(meta={
  'name': 'CounterFactualProto',
  'type': ['blackbox', 'tensorflow', 'keras'],
  'explanations': ['local'],
  'params': {
              'kappa': 0.0,
              'beta': 0.1,
              'feature_range': (array([ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.078, 21.   ]), array([ 15.  , 198.  , 122.  ,  63.  , 846.  ,  67.1 ,   2.42,  81.  ])),
              'gamma': 0.0,
              'theta': 10.0,
              'cat_vars': None,
              'ohe': False,
              'use_kdtree': False,
              'learning_rate_init': 0.01,
              'max_iterations': 1000,
              'c_init': 1.0,
              'c_steps': 10,
              'eps': (0.001, 0.001),
              'clip': (-1000.0, 1000.0),
              'update_num_grad': 1,
              'write_dir': None,
              'shape': (1, 8),
              'is_model': False,
              'is_model_keras': False,
              'is_ae': False,
              'is_ae_keras': False,
              'is_

In [107]:
print(f'Original prediction: {explanation.orig_class}')
print('Counterfactual prediction: {}'.format(explanation.cf['class']))

Original prediction: 0
Counterfactual prediction: 1


In [112]:
explanation = cf.explain(X)

In [113]:
explanation.all

{0: [],
 1: [],
 2: [],
 3: [array([[2.5628092e+00, 1.7726180e+02, 7.6516624e+01, 2.4388657e+01,
          7.2130630e+01, 2.6932917e+01, 7.8000002e-02, 2.2944651e+01]],
        dtype=float32)],
 4: [],
 5: [],
 6: [],
 7: [],
 8: [],
 9: []}

In [114]:
explanation.cf

{'X': array([[2.5628092e+00, 1.7726180e+02, 7.6516624e+01, 2.4388657e+01,
         7.2130630e+01, 2.6932917e+01, 7.8000002e-02, 2.2944651e+01]],
       dtype=float32),
 'class': 1,
 'proba': array([[0.4956944, 0.5043056]], dtype=float32),
 'grads_graph': array([[ -0.7179985 ,  -5.005951  ,  23.374054  ,  -0.96334076,
           3.8287811 , -13.371899  ,  -0.38599998,  -5.9150696 ]],
       dtype=float32),
 'grads_num': array([[  18.74566078,   38.92183304, -117.42114276,   24.19948392,
          -35.82239151,   62.04843149,   93.54948252,   25.92801861]])}

In [116]:
explanation.orig_class

0

In [117]:
explanation.orig_proba

array([[0.9228061 , 0.07719394]], dtype=float32)

In [118]:
X

array([[  3.   , 180.   ,  64.   ,  25.   ,  70.   ,  34.   ,   0.271,
         26.   ]])

In [1]:
import tensorflow as tf
tf.get_logger().setLevel(40) # suppress deprecation messages
tf.compat.v1.disable_v2_behavior() # disable TF2 behaviour as alibi code still relies on TF1 constructs
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.utils import to_categorical
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import os
from sklearn.datasets import load_boston
from alibi.explainers import CounterFactualProto

print('TF version: ', tf.__version__)
print('Eager execution enabled: ', tf.executing_eagerly()) # False

TF version:  2.4.1
Eager execution enabled:  False


In [2]:
boston = load_boston()
data = boston.data
target = boston.target
feature_names = boston.feature_names

In [3]:
y = np.zeros((target.shape[0],))
y[np.where(target > np.median(target))[0]] = 1


In [4]:
data = np.delete(data, 3, 1)
feature_names = np.delete(feature_names, 3)

In [5]:
mu = data.mean(axis=0)
sigma = data.std(axis=0)
data = (data - mu) / sigma

In [6]:
idx = 475
x_train,y_train = data[:idx,:], y[:idx]
x_test, y_test = data[idx:,:], y[idx:]
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [7]:
np.random.seed(42)
tf.random.set_seed(42)

In [8]:
def nn_model():
    x_in = Input(shape=(12,))
    x = Dense(40, activation='relu')(x_in)
    x = Dense(40, activation='relu')(x)
    x_out = Dense(2, activation='softmax')(x)
    nn = Model(inputs=x_in, outputs=x_out)
    nn.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
    return nn

In [9]:
nn = nn_model()
nn.summary()
nn.fit(x_train, y_train, batch_size=64, epochs=500, verbose=0)
nn.save('nn_boston.h5', save_format='h5')

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 12)]              0         
_________________________________________________________________
dense (Dense)                (None, 40)                520       
_________________________________________________________________
dense_1 (Dense)              (None, 40)                1640      
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 82        
Total params: 2,242
Trainable params: 2,242
Non-trainable params: 0
_________________________________________________________________


In [10]:
nn = load_model('nn_boston.h5')
score = nn.evaluate(x_test, y_test, verbose=0)
print('Test accuracy: ', score[1])

Test accuracy:  0.83870965


`Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.


In [11]:
X = x_test[1].reshape((1,) + x_test[1].shape)
shape = X.shape

In [12]:
# define model
nn = load_model('nn_boston.h5')

# initialize explainer, fit and generate counterfactual
cf = CounterFactualProto(nn, shape, use_kdtree=True, theta=10., max_iterations=1000,
                         feature_range=(x_train.min(axis=0), x_train.max(axis=0)),
                         c_init=1., c_steps=10)

cf.fit(x_train)
explanation = cf.explain(X)

No encoder specified. Using k-d trees to represent class prototypes.


In [13]:
print(f'Original prediction: {explanation.orig_class}')
print('Counterfactual prediction: {}'.format(explanation.cf['class']))

Original prediction: 0
Counterfactual prediction: 1


In [14]:
orig = X * sigma + mu
counterfactual = explanation.cf['X'] * sigma + mu
delta = counterfactual - orig
for i, f in enumerate(feature_names):
    if np.abs(delta[0][i]) > 1e-4:
        print('{}: {}'.format(f, delta[0][i]))

AGE: -5.954782076362235
LSTAT: -4.8512767599363364


In [15]:
print('% owner-occupied units built prior to 1940: {}'.format(orig[0][5]))
print('% lower status of the population: {}'.format(orig[0][11]))

% owner-occupied units built prior to 1940: 93.6
% lower status of the population: 18.68


In [16]:
os.remove('nn_boston.h5')